apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-league-owner-portal
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/timeout: "900"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 900
      containers:
      - image: gcr.io/PROJECT_ID/frontend-league-owner-portal
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"